export type { Sip009NftTraitContract } from './traits/sip009-nft-trait';
export type { Sip010FtTraitContract } from './traits/sip010-ft-trait';
export type { ProposalTraitContract } from './traits/proposal-trait';
export type { ExtensionTraitContract } from './traits/extension-trait';
export type { DaoContract } from './dao';
export type { TokenContract } from './token';
export type { VaultContract } from './vault';
export type { VoteContract } from './vote';
export type { SubmissionContract } from './submission';
export declare const contracts: {
    sip009NftTrait: import("@clarigen/core").Contract<import("./traits/sip009-nft-trait").Sip009NftTraitContract>;
    sip010FtTrait: import("@clarigen/core").Contract<import("./traits/sip010-ft-trait").Sip010FtTraitContract>;
    proposalTrait: import("@clarigen/core").Contract<import("./traits/proposal-trait").ProposalTraitContract>;
    extensionTrait: import("@clarigen/core").Contract<import("./traits/extension-trait").ExtensionTraitContract>;
    dao: import("@clarigen/core").Contract<import("./dao").DaoContract>;
    token: import("@clarigen/core").Contract<import("./token").TokenContract>;
    vault: import("@clarigen/core").Contract<import("./vault").VaultContract>;
    vote: import("@clarigen/core").Contract<import("./vote").VoteContract>;
    submission: import("@clarigen/core").Contract<import("./submission").SubmissionContract>;
};
