// CONTRACTS
export const CONTRACTS = {
  DAO: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.core-dao",
};

export const EXTENSIONS: {
  TREASURY: string,
  SUBMISSION: string,
  VOTING: string,
} = {
  TREASURY: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.treasury",
  SUBMISSION: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.proposal-submission",
  VOTING: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.proposal-voting",
};

export const GOVERNANCE: { TOKEN: string } = {
  TOKEN: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.nft",
}

export const BOOTSTRAPS: { BOOTSTRAP: string } = {
  BOOTSTRAP: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.bootstrap",
};

export const PROPOSALS: { TRANSFER_NFT: string } = {
  TRANSFER_NFT: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.transfer-nft",
};

// ERROR CODES
export enum DAO_CODES {
  ERR_UNAUTHORIZED = 1000,
  ERR_ALREADY_EXECUTED = 1001,
  ERR_INVALID_EXTENSION = 1002,
};