// CONTRACTS
export const CONTRACTS = {
  DAO: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.core-dao",
};

export const EXTENSIONS: {
  TREASURY: string,
  SUBMISSION: string,
  VOTING: string,
  INVESTMENT_CLUB: string,
  EMERGENCY_PROPOSE: string,
  EMERGENCY_EXECUTE: string
} = {
  TREASURY: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.treasury",
  SUBMISSION: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.proposal-submission",
  VOTING: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.proposal-voting",
  INVESTMENT_CLUB: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.investment-club",
  EMERGENCY_PROPOSE: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.emergency-proposals",
  EMERGENCY_EXECUTE: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.emergency-execute",
};

export const GOVERNANCE: { TOKEN: string, MEMBERSHIP: string } = {
  TOKEN: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.club-governance-token",
  MEMBERSHIP: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.club-membership-nft",
}

export const BOOTSTRAPS: { BOOTSTRAP: string } = {
  BOOTSTRAP: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.bootstrap",
};

export const PROPOSALS: { DISTRIBUTE_TOKENS: string } = {
  DISTRIBUTE_TOKENS: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.transfer-tokens",
};

// ERROR CODES
export enum DAO_CODES {
  ERR_UNAUTHORIZED = 1000,
  ERR_ALREADY_EXECUTED = 1001,
  ERR_INVALID_EXTENSION = 1002,
};