// CONTRACTS
export const CONTRACTS = {
  DAO: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.core-dao",
};

export const EXTENSIONS: {
  TREASURY: string,
  SUBMISSION: string,
  VOTING: string,
  EMERGENCY_PROPOSE: string,
  EMERGENCY_EXECUTE: string
} = {
  TREASURY: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.treasury",
  SUBMISSION: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.proposal-submission",
  VOTING: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.proposal-voting",
  EMERGENCY_PROPOSE: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.emergency-proposals",
  EMERGENCY_EXECUTE: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.emergency-execute",
};

export const GOVERNANCE: { TOKEN: string } = {
  TOKEN: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.token",
}

export const BOOTSTRAPS: { BOOTSTRAP: string } = {
  BOOTSTRAP: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.bootstrap",
};

export const PROPOSALS: { TRANSFER_TOKENS: string, TRANSFER_STX: string } = {
  TRANSFER_TOKENS: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.transfer-tokens",
  TRANSFER_STX: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.transfer-stx",
};

// ERROR CODES
export enum DAO_CODES {
  ERR_UNAUTHORIZED = 1000,
  ERR_ALREADY_EXECUTED = 1001,
  ERR_INVALID_EXTENSION = 1002,
};