[project]
name = "stacksos/template"
authors = []
description = ""
telemetry = false
requirements = []
cache_dir = "/Users/ryanwaits/.clarinet/cache"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.bootstrap]
path = "contracts/proposals/bootstrap.clar"

[contracts.club-governance-token]
path = "contracts/extensions/membership/club-governance-token.clar"

[contracts.club-governance-token-trait]
path = "contracts/traits/club-governance-token-trait.clar"

[contracts.club-membership-nft]
path = "contracts/extensions/membership/club-membership-nft.clar"

[contracts.club-membership-nft-trait]
path = "contracts/traits/club-membership-nft-trait.clar"

[contracts.core-dao]
path = "contracts/core-dao.clar"

[contracts.distribute-funds]
path = "contracts/proposals/distribute-funds.clar"

[contracts.emergency-execute]
path = "contracts/extensions/emergencies/emergency-execute.clar"

[contracts.emergency-proposals]
path = "contracts/extensions/emergencies/emergency-proposals.clar"

[contracts.extension-trait]
path = "contracts/traits/extension-trait.clar"

[contracts.investment-club]
path = "contracts/extensions/investment-club.clar"

[contracts.proposal-submission]
path = "contracts/extensions/submissions/proposal-submission.clar"

[contracts.proposal-trait]
path = "contracts/traits/proposal-trait.clar"

[contracts.proposal-voting]
path = "contracts/extensions/voting/proposal-voting.clar"

[contracts.sip10-trait]
path = "contracts/traits/sip10-trait.clar"

[contracts.sip9-trait]
path = "contracts/traits/sip9-trait.clar"

[contracts.treasury]
path = "contracts/extensions/treasury.clar"

[contracts.voting-trait]
path = "contracts/traits/voting-trait.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
